apiVersion: networking.dn-lab.io/v1alpha1
kind: Kokotap
metadata:
  labels:
    app.kubernetes.io/name: kokotap
    app.kubernetes.io/instance: kokotap-sample
    app.kubernetes.io/part-of: dn-vtap
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dn-vtap
  name: kokotap-sample
spec:
  podName: "ueransim-gnb-ues-6c7d5c7bfb-rb4q6"
  destIp: "192.168.1.109"
  vxlanID: "1000"
  namespace: "default"
  mirrorType: "both"
  podInterface: "eth0"
  image: "netand593/kokotap:2.0-beta"
  
  # TODO(user): Add fields here
